# Generated by Django 4.1.7 on 2023-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=255),
        ),
    ]
